---
- name: Symlink config files in rc folder
  file: src=/vagrant/roles/dotfiles/files/{{ item }} dest=/home/vagrant/{{ item }} state=link
  with_items:
    - .bashrc_mods
    - .bash_aliases
    - .tmux.conf
- name: Create empty .bash_aliases_local file
  shell:
      echo '# Add local aliases here' > /home/vagrant/.bash_aliases_local
      creates=/home/vagrant/.bash_aliases_local
- name: Include .bashrc_mods in .bashrc
  lineinfile:
      "dest=/home/vagrant/.bashrc line='. ~/.bashrc_mods # Include local mods' insertafter=EOF"
