---
- name: Check if swap file exists
  stat:
    path: "{{swap_file_path}}"
  register: swap_file_check
  tags:
    - swap.file.check

- name: Create swap file
  command: fallocate -l {{swap_file_size}} {{swap_file_path}}
  when: not swap_file_check.stat.exists
  tags:
    - swap.file.create

- name: Change swap file permissions
  file: path="{{swap_file_path}}"
        owner=root
        group=root
        mode=0600
  when: not swap_file_check.stat.exists
  tags:
    - swap.file.permissions

- name: Format swap file
  command: mkswap {{swap_file_path}}
  when: not swap_file_check.stat.exists
  tags:
    - swap.file.mkswap

- name: Write swap entry in fstab
  mount: name=none
         src={{swap_file_path}}
         fstype=swap
         opts=sw
         passno=0
         dump=0
         state=present
  when: not swap_file_check.stat.exists
  tags:
    - swap.fstab

- name: Turn on swap
  command: swapon -a
  when: not swap_file_check.stat.exists
  tags:
    - swap.turn.on

- name: Set swappiness
  sysctl:
    name: vm.swappiness
    value: "{{swappiness}}"
  when: not swap_file_check.stat.exists
  tags:
    - swap.set.swappiness
